### ISSUE TITLE
0% infill not being recognized 

### ISSUE THREAD

**Issue by synsuiter** [SynDaverCO/symple-slicer#182]
**Describe the bug**
Unable to Slice with 0% infill. 

**Details**
 - SympleSlicer Version: BETA v1.2.0
 - Browser : Chrome

**To Reproduce**
1. Open SS
2. Load model and any profile
3. set the infill % to 0
4. Slice
5. You will see it is at a higher % than 0. 

**Expected behavior**
It should accept 0% infill.

**Screenshots**
![0percent-infill_001](https://user-images.githubusercontent.com/65256117/194366099-48ae0366-38ba-49e7-ab3e-352136aa08b5.PNG)
![0percent-infill_002](https://user-images.githubusercontent.com/65256117/194366100-fe1e6fc5-3598-4be4-9f35-f650799c019d.PNG)

**Comment by marciot** [comment]
The "Infill Density" (infill_sparse_density) only indirectly controls the infill via the "Infill Line Distance" (infill_line_distance) setting. If no "infill_line_distance" was specified in the profile, then changing the "infill_sparse_density" would cause "infill_line_distance" to recompute, and thus the model would be changed appropriately. However, because the profile is setting "infill_line_distance" to be a certain value, changing "infill_sparse_density" has no effect. The user would need to change "infill_line_distance"

This is because as it stands, any values explicitly set in the profile will be blocked from being automatically recomputed based on other values. If you do not think this is appropriate, we could eliminate that requirement. It's just unclear as to what really makes sense, so I had to make decision one way of another.

**Comment by synsuiter** [comment]
Ahh yeah, this makes sense and I can can update some of the profile stuff to correct this. I will close this out
