### ISSUE TITLE
Version number not showing on fresh load

### ISSUE THREAD

**Issue by SynWillinger** [SynDaverCO/symple-slicer#77]
**Describe the bug**
When Symple Slicer is first loaded after a full browser history clear, it is not showing the version number on the splash screen. Was showing the number when memory was not cleared and it had been updated through the updater. 

**Details**
 - SympleSlicer Version: 1.0.6
 - Browser: Chrome

**To Reproduce**
1. Go to "Clear browsing data"
2. Click on all check boxes in both Basic and Advanced and then "clear data"
3. Open Symple Slicer

**Expected behavior**
Version number should be displayed, so we can be sure what version a user is using.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/60902184/85182554-4b5c0c80-b246-11ea-8360-4114cef841ff.PNG)

**Additional context**

**Comment by marciot** [comment]
This is a known issue. It has been this way for a while. There are no easy solutions but I have been thinking about it.

**Comment by marciot** [comment]
Just to provide more context, the version number pertains to the version stored in cache. During the initial load, it is not using a cached version, hence no version number appears. I am thinking that the way around this problem is to present the user with an "installing" screen the first time they load the page, then force a refresh into the cached version. This would avoid this anomalous state where they are using an uncached version.

**Comment by marciot** [comment]
It will now always show the update dialog box on first run, which will force the version number to appear when the user clicks "Update!"

**Comment by marciot** [comment]
@SynWillinger: Can this ticket be closed?
